def resolve_altool!
  candidates = [
    '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDelivery.framework/Resources/altool',
    '/Applications/Xcode.app/Contents/Developer/usr/bin/altool',
    '/Applications/Xcode_26.3.app/Contents/SharedFrameworks/ContentDelivery.framework/Resources/altool',
    '/Applications/Xcode_26.3.app/Contents/Developer/usr/bin/altool'
  ]
  altool = candidates.find { |p| File.exist?(p) } || `xcrun -f altool`.strip
  legacy = '/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool'
  sh("mkdir -p \"#{File.dirname(legacy)}\"")
  sh("ln -sf \"#{altool}\" \"#{legacy}\"")
end

def latest_ipa
  ipa = ENV['IPA_PATH'] || Dir['build/StunFun-signed.ipa', 'build/export/*.ipa'].find { |p| File.exist?(p) }
  UI.user_error!('No signed IPA found') unless ipa && File.exist?(ipa)
  ipa
end

def use_api_key_auth?
  ENV['APP_STORE_CONNECT_API_KEY_ID'].to_s.length > 0 && ENV['APP_STORE_CONNECT_API_ISSUER_ID'].to_s.length > 0
end

platform :ios do
  desc 'Upload the signed Stun Fun IPA using XCTEQ/fastlane-plugin-altool'
  lane :upload_altool do
    resolve_altool!
    if use_api_key_auth?
      UI.message('Using App Store Connect API key auth via xcrun altool (plugin only supports Apple ID password auth).')
      sh("xcrun altool --upload-app --type ios --file \"#{latest_ipa}\" --apiKey \"#{ENV['APP_STORE_CONNECT_API_KEY_ID']}\" --apiIssuer \"#{ENV['APP_STORE_CONNECT_API_ISSUER_ID']}\" --verbose")
    else
      altool(
        altool_username: ENV['FASTLANE_USER'],
        altool_password: ENV['FASTLANE_PASSWORD'],
        altool_app_type: 'ios',
        altool_ipa_path: latest_ipa,
        altool_output_format: 'normal'
      )
    end
  end
end
